USE [master]
GO

/****** Object:  Database [Appointment]    Script Date: 4/17/2022 5:47:59 PM ******/
CREATE DATABASE [Appointment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Appointment', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Appointment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Appointment_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Appointment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Appointment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Appointment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Appointment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Appointment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Appointment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Appointment] SET ARITHABORT OFF 
GO

ALTER DATABASE [Appointment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Appointment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Appointment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Appointment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Appointment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Appointment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Appointment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Appointment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Appointment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Appointment] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Appointment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Appointment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Appointment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Appointment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Appointment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Appointment] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Appointment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Appointment] SET RECOVERY FULL 
GO

ALTER DATABASE [Appointment] SET  MULTI_USER 
GO

ALTER DATABASE [Appointment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Appointment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Appointment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Appointment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Appointment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Appointment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Appointment] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Appointment] SET  READ_WRITE 
GO


